---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions: {}

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      npm-development:
        dependency-type: development
      npm-production:
        dependency-type: production
