---
name: "filter-feed-by-likes-action"
description: "いいね数などで記事を評価しフィルタしたフィードを生成する"
author: "bishishin"

branding:
  icon: "rss"
  color: "orange"

inputs:
  original:
    description: "生成元フィードの入力ファイルパス。前段のステップでローカルにダウンロードしておくことを想定"
    required: true
  cache:
    description: |
      配信済みフィードの入力ファイルパス。
      ここに含まれる配信済み記事は、評価および配信の再処理を行わない。
      また元フィードからは消えた配信済み記事を含めるために用いる。
      前回配信分のファイルを流用することを想定。
  output:
    description: "生成フィードの出力ファイルパス。"
    required: true
  threshold:
    description: "配信する評価の閾値"
    default: "10"
  validate-mime-types:
    description: "type属性のMIMEタイプバリデーションを有効にするかどうか"
    default: "true"
  default-mime-type:
    description: "不正なMIMEタイプを検出した場合のデフォルト値"
    default: "image/jpeg"

runs:
  using: node20
  main: dist/index.js
